#!/bin/bash

for id in `ps -ef | grep producer | tr -s ' ' | cut -d' ' -f 2`; \
do kill -9 $id;
 done

for id in `ps -ef | grep consumer | tr -s ' ' | cut -d' ' -f 2`; \
do kill -9 $id; 
 done

Run=`ps -ef | grep consumer | tr -s ' ' | cut -d' ' -f 2`

kill -9 $Run

IPCS_S=`ipcs -s | grep miller | cut -f2 -d" "`
IPCS_M=`ipcs -m | grep miller | cut -f2 -d" "`



for id in $IPCS_M; do
  ipcrm -m $id;
done

for id in $IPCS_S; do
  ipcrm -s $id;
done

